/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package psp1.vista;

import java.io.File;
import java.text.DecimalFormat;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import psp1.utilidades.Estadistica;
import psp1.utilidades.Fichero;

/**
 *
 * @author Juan Carlos
 */
public class VistaGrafica extends javax.swing.JFrame {

    File file;

    /**
     * Creates new form VistaGraficaTest
     */
    public VistaGrafica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfRutaArchivo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btSeleccionarFichero = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btCalcularMedia = new javax.swing.JButton();
        btCalcularDesviacion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDatos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfDesviacion = new javax.swing.JTextField();
        tfMedia = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tfRutaArchivo.setEditable(false);
        tfRutaArchivo.setToolTipText("");

        jLabel1.setText("Seleccione el archivo con la lista de numeros separados por enter:");

        btSeleccionarFichero.setText("Seleccionar");
        btSeleccionarFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSeleccionarFicheroActionPerformed(evt);
            }
        });

        jLabel2.setText("Archivo Seleccionado:");

        btCalcularMedia.setText("Calcular Media");
        btCalcularMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcularMediaActionPerformed(evt);
            }
        });

        btCalcularDesviacion.setText("Calcular Desviación Estandar");
        btCalcularDesviacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcularDesviacionActionPerformed(evt);
            }
        });

        tbDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Valores del Archivo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbDatos);

        jLabel3.setText("Media:");

        jLabel4.setText("Desviación Estandar:");

        tfDesviacion.setEditable(false);

        tfMedia.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSeleccionarFichero))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfRutaArchivo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btCalcularMedia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btCalcularDesviacion, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfDesviacion, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(65, 65, 65))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btSeleccionarFichero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfRutaArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCalcularMedia)
                    .addComponent(btCalcularDesviacion))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfDesviacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCalcularMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcularMediaActionPerformed
        if (file != null) {
            List<Double> datos = Fichero.leerFichero(file.getAbsolutePath());
            if (datos == null) {
                limpiarFormularios();
                JOptionPane.showMessageDialog(rootPane, "Se ha producido un error leyendo el archivo", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                llenarTabla(datos);
                double media = Estadistica.calcularMedia(datos);
                DecimalFormat df = new DecimalFormat("0.00000");
                tfMedia.setText(df.format(media));
            }
        } else {
            limpiarFormularios();
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un archivo primero", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btCalcularMediaActionPerformed

    private void btCalcularDesviacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcularDesviacionActionPerformed
        if (file != null) {
            List<Double> datos = Fichero.leerFichero(file.getAbsolutePath());
            if (datos == null) {
                limpiarFormularios();
                JOptionPane.showMessageDialog(rootPane, "Se ha producido un error leyendo el archivo", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                llenarTabla(datos);
                double desviacion = Estadistica.calcularDesviacionEstandar(datos);
                DecimalFormat df = new DecimalFormat("0.00000"); 
                tfDesviacion.setText(df.format(desviacion));
            }
        } else {
            limpiarFormularios();
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un archivo primero", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btCalcularDesviacionActionPerformed

    private void btSeleccionarFicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSeleccionarFicheroActionPerformed
        JFileChooser jFileChooser = new JFileChooser();
        int result = jFileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            file = jFileChooser.getSelectedFile();
            tfRutaArchivo.setText(file.getName());
        }
    }//GEN-LAST:event_btSeleccionarFicheroActionPerformed

    /**
     * metodo usado para mostrar los datos leidos del archivo
     * @param datos 
     */
    private void llenarTabla(List<Double> datos) {
        Object[][] datosTabla = new Object[datos.size()][1];
        int i = 0;
        for (Double dato : datos) {
            datosTabla[i][0] = dato;
            i++;
        }
        tbDatos.setModel(new javax.swing.table.DefaultTableModel(
                datosTabla,
                new String[]{"Valores del Archivo"}) {
                    Class[] types = new Class[]{
                        java.lang.Double.class
                    };
                    boolean[] canEdit = new boolean[]{
                        false
                    };
                });
    }

    /**
     * metodo usado para limpiar los datos actuales de la tabla, la media
     * y la desviacion
     */
    private void limpiarFormularios() {
        tfDesviacion.setText("");
        tfMedia.setText("");
        tbDatos.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{"Valores del Archivo"}) {
                    Class[] types = new Class[]{
                        java.lang.Double.class
                    };
                    boolean[] canEdit = new boolean[]{
                        false
                    };
                });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaGrafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCalcularDesviacion;
    private javax.swing.JButton btCalcularMedia;
    private javax.swing.JButton btSeleccionarFichero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbDatos;
    private javax.swing.JTextField tfDesviacion;
    private javax.swing.JTextField tfMedia;
    private javax.swing.JTextField tfRutaArchivo;
    // End of variables declaration//GEN-END:variables
}
